#!/bin/sh

setup() {
    LANG=C
    LC_ALL=C
    CONFIG=${1:-config/sync.conf}

    SCRIPT_HOME=$(cd "$(dirname "$0")" && pwd)/..
    . "${SCRIPT_HOME}/${CONFIG}"

    EXECDIR=$(dirname "$0")
    DATE=$(date +%Y%m%d)
}

send_mail_to_admin() {
    cat -v "$JOBLOG" | nkf -w | \
      mail -s "[cron][$(hostname)] Deferred Sync Log" \
      "$ADMIN_MAIL_ADDRESS"
}

deferred_sync() {
    {
        echo -n "*** $0: Job started on $(hostname) at "
        date "+%Y/%m/%d %T"
    } >>"$JOBLOG" 2>&1

    [ -n "$STARTSCRIPT" ] && . "$STARTSCRIPT" >>"$JOBLOG" 2>&1
    . "$SCRIPT_HOME/lib/load" >>"$JOBLOG" 2>&1
    [ -n "$ENDSCRIPT" ] && . "$ENDSCRIPT" >>"$JOBLOG" 2>&1

    {
        echo -n "*** $0: Job ended on $(hostname) at "
        date "+%Y/%m/%d %T"
        echo
    } >>"$JOBLOG" 2>&1

    case "$ADMIN_MAIL_ADDRESS" in
      *@*) send_mail_to_admin ;;
    esac
}

main() {
    setup "$@"
    deferred_sync
}

main "$@"
