#!/bin/sh

echo "- endscript loaded"

######################
# テスト実行後の処理 #
######################

# バックアップを削除
test -d $SCRIPT_HOME/test/backup && \
  rm -vrf $SCRIPT_HOME/test/backup
test -f $SCRIPT_HOME/test/svndump/test.zip && \
  rm -vrf $SCRIPT_HOME/test/svndump/test.zip

