#!/bin/sh

echo -n "- [info] endscript has been loaded at "
date "+%Y/%m/%d %T"

######################
# テスト実行後の処理 #
######################

# バックアップを削除
test -d $SCRIPT_HOME/test/backup/svndump && \
  rm -vrf $SCRIPT_HOME/test/backup/svndump
test -f $SCRIPT_HOME/test/svndump/test.zip && \
  rm -vrf $SCRIPT_HOME/test/svndump/test.zip

