#!/bin/sh

echo "- endscript loaded"

######################
# テスト実行後の処理 #
######################

# 当日分のバックアップの削除
test -d $SCRIPT_HOME/test/backup/_backup_$DATE && \
  rm -vrf $SCRIPT_HOME/test/backup/_backup_$DATE

# バックアップを削除
test -d $SCRIPT_HOME/test/backup/svndump && \
  rm -vrf $SCRIPT_HOME/test/backup/svndump
test -f $SCRIPT_HOME/test/svndump/test.zip && \
  rm -vrf $SCRIPT_HOME/test/svndump/test.zip
test -d $SCRIPT_HOME/test/mongodbdump.zip && \
  rm -vrf $SCRIPT_HOME/test/mongodbdump

# リモートから転送されてきたディレクトリを削除
test -d $SCRIPT_HOME/test/remote/backup && \
  rm -vrf $SCRIPT_HOME/test/remote/backup

