#!/bin/sh

echo "- endscript loaded"

######################
# テスト実行後の処理 #
######################

# 当日分のバックアップの削除
test -d $SCRIPT_HOME/test/backup/_backup_$DATE && \
  rm -vrf $SCRIPT_HOME/test/backup/_backup_$DATE

# テスト実行日より 1 ～ 5 日前のバックアップを
# 削除する。
TEST_EXPIRE_1=`date +%Y%m%d -d "1 days ago"`
TEST_EXPIRE_2=`date +%Y%m%d -d "2 days ago"`
TEST_EXPIRE_3=`date +%Y%m%d -d "3 days ago"`
TEST_EXPIRE_4=`date +%Y%m%d -d "4 days ago"`
TEST_EXPIRE_5=`date +%Y%m%d -d "5 days ago"`
rm -vrf $SCRIPT_HOME/test/backup/_backup_$TEST_EXPIRE_1
rm -vrf $SCRIPT_HOME/test/backup/_backup_$TEST_EXPIRE_2
rm -vrf $SCRIPT_HOME/test/backup/_backup_$TEST_EXPIRE_3
rm -vrf $SCRIPT_HOME/test/backup/_backup_$TEST_EXPIRE_4
rm -vrf $SCRIPT_HOME/test/backup/_backup_$TEST_EXPIRE_5

# バックアップを削除
test -d $SCRIPT_HOME/test/backup/svndump && \
  rm -vrf $SCRIPT_HOME/test/backup/svndump
test -f $SCRIPT_HOME/test/svndump/test.zip && \
  rm -vrf $SCRIPT_HOME/test/svndump/test.zip

# リモートから転送されてきたディレクトリを削除
test -d $SCRIPT_HOME/test/remote/backup && \
  rm -vrf $SCRIPT_HOME/test/remote/backup

