#!/bin/sh

echo -n "- [info] endscript has been loaded at "
date "+%Y/%m/%d %T"

######################
# テスト実行後の処理 #
######################

# 当日分のバックアップの削除
test -d $SCRIPT_HOME/test/backup/_backup_$DATE && \
  rm -vrf $SCRIPT_HOME/test/backup/_backup_$DATE

# バックアップを削除
test -d $SCRIPT_HOME/test/backup/svndump && \
  rm -vrf $SCRIPT_HOME/test/backup/svndump
test -f $SCRIPT_HOME/test/svndump/test.zip && \
  rm -vrf $SCRIPT_HOME/test/svndump/test.zip
test -d $SCRIPT_HOME/test/mongodbdump.zip && \
  rm -vrf $SCRIPT_HOME/test/mongodbdump

# MongoDB Dump を削除
test -f $SCRIPT_HOME/test/mongodbdump.zip && \
  rm -vf $SCRIPT_HOME/test/mongodbdump.zip

# リモートから転送されてきたディレクトリを削除
test -d $SCRIPT_HOME/test/remote/backup && \
  rm -vrf $SCRIPT_HOME/test/remote/backup

