#!/bin/sh
#
# before - A script executed before the main deferred-sync process.
#
# This script is intended for pre-execution tasks, such as:
#   - Preparing temporary directories
#   - Checking system status before backup
#   - Logging the start of the sync process
#
# Note:
#   - Users can freely modify this script to include additional pre-execution logic.

printf -- "- [info] startscript has been loaded at "
date "+%Y/%m/%d %T"
