#!/bin/sh

load_plugin() {
    while [ $# -gt 0 ]
    do
        . $SCRIPT_HOME/lib/plugins/*$1
        shift
    done
}

load_plugins_by_config() {
    load_plugin $PLUGINS
}

load_plugins_all() {
    for PLUGIN in $SCRIPT_HOME/lib/plugins/*
    do
        . $PLUGIN
    done
    unset PLUGIN
}

load_plugins() {
    if [ $LOAD_PLUGINS_ALL = "true" ]; then
        load_plugins_all
    else
        load_plugins_by_config
    fi
}

load_plugins
