#!/bin/sh

echo -n "- [info] show_version has been loaded at "
date "+%Y/%m/%d %T"

test -x /opt/ruby/current/bin/ruby && /opt/ruby/current/bin/ruby -v
test -x /opt/python/current/bin/python && /opt/python/current/bin/python -V
test -x /opt/java/jdk/current/bin/java && /opt/java/jdk/current/bin/java -version
test -x /opt/go/current/bin/go && /opt/go/current/bin/go version
test -x /opt/mongo/current/bin/mongo && /opt/mongo/current/bin/mongo --version
test -x /opt/protobuf/current/bin/protoc && /opt/protobuf/current/bin/protoc --version
