#!/bin/sh
#
# 09_show_version - A script to display installed versions of key software.
#
# Outputs:
#   - Ruby version
#   - Python version
#   - Java version
#   - Go version
#   - MongoDB version
#   - Protocol Buffers version
#
# Note:
#   - This script assumes the respective software is installed in `/opt/<software>/current/bin/`.

printf -- "[INFO] - show_version has been loaded at "
date "+%Y/%m/%d %T"

[ -x /opt/ruby/current/bin/ruby ] && /opt/ruby/current/bin/ruby -v
[ -x /opt/python/current/bin/python ] && /opt/python/current/bin/python -V
[ -x /opt/java/jdk/current/bin/java ] && /opt/java/jdk/current/bin/java -version
[ -x /opt/go/current/bin/go ] && /opt/go/current/bin/go version
[ -x /opt/mongo/current/bin/mongo ] && /opt/mongo/current/bin/mongo --version
[ -x /opt/protobuf/current/bin/protoc ] && /opt/protobuf/current/bin/protoc --version
