#!/bin/sh
#
# 09_show_version - A script to display installed versions of key software.
#
# Outputs:
#   - Ruby version
#   - Python version
#   - Java version
#   - Go version
#   - MongoDB version
#   - Protocol Buffers version
#
# Note:
#   - This script assumes the respective software is installed in `/opt/<software>/current/bin/`.

start_message() {
    printf -- "[INFO] Loading: show_version has been loaded at "
    date "+%Y/%m/%d %T"
}

show_version() {
    [ -x /opt/ruby/current/bin/ruby ] && {
        echo "[INFO] Retrieving Ruby version"
        /opt/ruby/current/bin/ruby -v
    }

    [ -x /opt/python/current/bin/python ] && {
        echo "[INFO] Retrieving Python version"
        /opt/python/current/bin/python -V 2>&1
    }

    [ -x /opt/java/jdk/current/bin/java ] && {
        echo "[INFO] Retrieving Java version"
        /opt/java/jdk/current/bin/java -version
    }

    [ -x /opt/go/current/bin/go ] && {
        echo "[INFO] Retrieving Go version"
        /opt/go/current/bin/go version
    }

    [ -x /opt/mongo/current/bin/mongo ] && {
        echo "[INFO] Retrieving MongoDB version"
        /opt/mongo/current/bin/mongo --version
    }

    [ -x /opt/protobuf/current/bin/protoc ] && {
        echo "[INFO] Retrieving Protocol Buffers version"
        /opt/protobuf/current/bin/protoc --version
    }

    return 0
}

main() {
    start_message
    show_version
    return $?
}

main "$@"
