#!/bin/sh

echo -n "- [info] get_hardware_info has been loaded at "
date "+%Y/%m/%d %T"
which dmidecode > /dev/null && dmidecode --type system
which acpi > /dev/null && acpi -abi
which smartctl > /dev/null && test -b /dev/sda && smartctl -a /dev/sda
which smartctl > /dev/null && test -b /dev/sdb && smartctl -a /dev/sdb
which smartctl > /dev/null && test -b /dev/sdc && smartctl -a /dev/sdc
which smartctl > /dev/null && test -b /dev/sdd && smartctl -a /dev/sdd
which smartctl > /dev/null && test -b /dev/sde && smartctl -a /dev/sde
which smartctl > /dev/null && test -b /dev/sdf && smartctl -a /dev/sdf
