#!/bin/sh

update_debian_or_ubuntu() {
    test -f /etc/apt/sources.list && cat /etc/apt/sources.list
    apt-get update && \
      apt-get -y upgrade && \
      apt-get autoclean && \
      apt-get -y autoremove
    echo "Return code is $?"
}

update_redhat_or_centos() {
    test -f /etc/yum.conf && cat /etc/yum.conf
    yum -y update && \
      yum clean all
    echo "Return code is $?"
    package-cleanup -y --oldkernels --count $OLDKERNELS_COUNT
    echo "Return code is $?"
}

upgrade_from_network() {
    test -f /etc/debian_version && update_debian_or_ubuntu
    test -f /etc/redhat-release && update_redhat_or_centos
    which freshclam > /dev/null 2>&1 && freshclam
}

system_upgrade() {
    ping -c 1 debian.org > /dev/null 2>&1 && upgrade_from_network
    echo "Return code is $?"
}

echo -n "- [info] system_upgrade has been loaded at "
date "+%Y/%m/%d %T"
system_upgrade
