#!/bin/sh
#
# 20_system_upgrade - A script to upgrade the system packages based on the detected OS.
#
# Supported systems:
#   - Debian/Ubuntu (via apt-get)
#   - RedHat/CentOS (via yum)
#
# Required environment variables:
#   OLDKERNELS_COUNT : Number of old kernels to keep (for RHEL/CentOS).
#                      Example: 2
#
# Note:
#   - This script assumes that the system is connected to the internet and package managers are configured correctly.

start_message() {
    printf -- "[INFO] Loading: system_upgrade has been loaded at "
    date "+%Y/%m/%d %T"
}

update_debian_or_ubuntu() {
    [ -f /etc/apt/sources.list ] && cat /etc/apt/sources.list

    printf -- "[INFO] Executing: apt upgrade at "
    date "+%Y/%m/%d %T"

    apt-get update && \
      apt-get -y upgrade && \
      apt-get autoclean && \
      apt-get -y autoremove

    RC=$?
    echo "[INFO] Return code is $RC"
}

update_redhat_or_centos() {
    [ -f /etc/yum.conf ] && cat /etc/yum.conf

    printf -- "[INFO] Executing: yum update at "
    date "+%Y/%m/%d %T"

    yum -y update && yum clean all
    RC=$?
    echo "[INFO] Return code is $RC"

    package-cleanup -y --oldkernels --count "$OLDKERNELS_COUNT"
    RC=$?
    echo "[INFO] Return code is $RC"
}

freshclam_manually(){
    systemctl stop clamav-freshclam.service

    printf -- "[INFO] Executing: fleshclam at "
    date "+%Y/%m/%d %T"
    freshclam
    RC=$?
    echo "[INFO] Return code is $RC"

    systemctl start clamav-freshclam.service
}

upgrade_from_network() {
    [ -f /etc/debian_version ] && update_debian_or_ubuntu
    [ -f /etc/redhat-release ] && update_redhat_or_centos

    if command -v freshclam > /dev/null 2>&1; then
        freshclam_manually
    fi
}

system_upgrade() {
    if ping -c 1 debian.org > /dev/null 2>&1; then
        upgrade_from_network
    else
        printf -- "[WARN] Skipping upgrade: Network unavailable\n" >&2
    fi
}

main() {
    start_message
    system_upgrade
}

main "$@"
