#!/bin/sh
#
# 31_dump_postgresql - A script to dump the entire PostgreSQL database cluster and compress the dump.
#
# Required environment variables:
#   PGDUMP   : Directory where the dump files (SQL and compressed files) will be stored.
#              Example: /var/lib/postgresql/pg_dump
#   PG_USER  : PostgreSQL username.
#              Example: postgres
#
# Note:
#   - This script assumes that authentication is handled via ~/.pgpass

start_message() {
    printf -- "[INFO] Loading: dump_postgresql has been loaded at "
    date "+%Y/%m/%d %T"
}

dump_postgresql() {
    # Remove existing compressed dump if it exists
    [ -f "$PGDUMP/all.dump.gz" ] && rm "$PGDUMP/all.dump.gz"

    # Change directory to PGDUMP to ensure correct permissions
    cd "$PGDUMP" || return 1

    printf -- "[INFO] Executing: pg_dumpall at "
    date "+%Y/%m/%d %T"

    # Perform the dump and compress the output using sudo
    sudo -u "$PG_USER" sh -c "pg_dumpall -c > 'all.dump' && gzip -f 'all.dump'"

    RC=$?
    echo "[INFO] Return code is $RC"
    return $RC
}

main() {
    start_message
    dump_postgresql
    return $?
}

main "$@"
