#!/bin/sh

get_remote() {
    OPTS="-avz --delete -e ssh"
    if [ "$DRY_RUN" = "true" ]; then
        OPTS="$OPTS --dry-run"
    fi
    if [ -d $GET_TARGET_DIR ]; then
        echo "rsync $OPTS $REMOTE_USER@$1:$2 $GET_TARGET_DIR/$1"
        ping -c 1 $1 > /dev/null 2>&1 && \
          rsync $OPTS $REMOTE_USER@$1:$2 $GET_TARGET_DIR/$1
        echo "Return code is $?"
    fi
}

get_remote_dir() {
    echo -n "* Executing get remote dir at "
    date "+%Y/%m/%d %T"
    for GET_HOST in $GET_HOSTS
    do
        for GET_REMOTE_DIR in $GET_REMOTE_DIRS
        do
            get_remote $GET_HOST $GET_REMOTE_DIR
        done
    done
    unset REMOTE_HOST
}

echo -n "- [info] get_remote_dir has been loaded at "
date "+%Y/%m/%d %T"
get_remote_dir
